version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  environment = [
    "jest",
    "browser",
    "nodejs"
  ]
  style_guide = "airbnb"
  plugins = ["react"]
